[package]
name = "employee-management"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "3.1.0"
rpassword = "5.0.1"
bcrypt = "0.11.0"
dotenv = "0.15.0"
